export enum Routes {
  LoginStack = 'LoginStack',
  IntroScreen = 'IntroScreen',
  LoggedInStack = 'LoggedInStack',
  HomeScreen = 'HomeScreen',
  LoginScreen = 'LoginScreen',
  RegisterScreen = 'RegisterScreen',
  RegisterInfoScreen = 'RegisterInfoScreen',
  ForgotPassScreen = 'ForgotPassScreen',
  UserScreen = 'UserScreen',
  AccSettingsScreen = 'AccSettingsScreen',
  ChangePasswordScreen = 'ChangePasswordScreen',
  RaportsScreen = 'RaportsScreen',
  MainScreen = 'MainScreen',
  SettingsStack = 'SettingsStack',
}